version: '3.7'

services:
  web:
    build: ./
    volumes:
      - ./:/usr/api/
    env_file:
      - .env
    ports:
      - 8002:8000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "stac"
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27018:27017"